version: '3'
volumes:
  postgres_your_rents_data:
      driver: local
services:
    adminer:
        image: adminer:4.8.1
        restart: 'no'
        ports:
          - 18080:8080
        environment:
          ADMINER_DEFAULT_SERVER: postgres_your_rents
        networks:
          - your-rents-network
    postgres_your_rents:
      image: postgres:13
      volumes:
        - postgres_your_rents_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: your_rents
        POSTGRES_USER: your_rents
        POSTGRES_PASSWORD: your_rents
      ports:
        - 25432:5432
      networks:
        - your-rents-network
networks:
    your-rents-network:
        driver: bridge
