## Spring Configuration
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:25432/your_rents'
    username: 'your_rents'
    password: 'your_rents'
    driver-class-name: 'org.postgresql.Driver'
